//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDV.Desktop.I18n;

using System.Resources;
using System.Globalization;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{
    private static ResourceManager? resourceMan;

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() { }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                ResourceManager temp = new ResourceManager("PDV.Desktop.I18n.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture { get; set; }

    private static string GetString(string name)
    {
        return ResourceManager.GetString(name, Culture) ?? $"[{name}]";
    }

    // ==================== GLOBAL ====================
    public static string Global_Btn_Save => GetString("Global_Btn_Save");
    public static string Global_Btn_Cancel => GetString("Global_Btn_Cancel");
    public static string Global_Btn_Close => GetString("Global_Btn_Close");
    public static string Global_Btn_Search => GetString("Global_Btn_Search");
    public static string Global_Btn_Confirm => GetString("Global_Btn_Confirm");
    public static string Global_Btn_Edit => GetString("Global_Btn_Edit");
    public static string Global_Btn_Delete => GetString("Global_Btn_Delete");
    public static string Global_Btn_Refresh => GetString("Global_Btn_Refresh");
    public static string Global_Btn_Print => GetString("Global_Btn_Print");
    public static string Global_Btn_Previous => GetString("Global_Btn_Previous");
    public static string Global_Btn_Next => GetString("Global_Btn_Next");
    public static string Global_Btn_Clear => GetString("Global_Btn_Clear");
    public static string Global_Lbl_Loading => GetString("Global_Lbl_Loading");
    public static string Global_Lbl_Ready => GetString("Global_Lbl_Ready");
    public static string Global_Lbl_Status => GetString("Global_Lbl_Status");
    public static string Global_Lbl_Total => GetString("Global_Lbl_Total");
    public static string Global_Lbl_Date => GetString("Global_Lbl_Date");
    public static string Global_Lbl_Actions => GetString("Global_Lbl_Actions");
    public static string Global_Lbl_PageOf => GetString("Global_Lbl_PageOf");
    public static string Global_Lbl_Today => GetString("Global_Lbl_Today");
    public static string Global_Lbl_ThisWeek => GetString("Global_Lbl_ThisWeek");
    public static string Global_Lbl_ThisMonth => GetString("Global_Lbl_ThisMonth");
    public static string Global_Msg_Error => GetString("Global_Msg_Error");
    public static string Global_Msg_NotFound => GetString("Global_Msg_NotFound");
    public static string Global_Lbl_Unknown => GetString("Global_Lbl_Unknown");
    public static string Global_Lbl_Yes => GetString("Global_Lbl_Yes");
    public static string Global_Lbl_No => GetString("Global_Lbl_No");
    public static string Global_Lbl_All => GetString("Global_Lbl_All");
    public static string Global_Lbl_StartDate => GetString("Global_Lbl_StartDate");
    public static string Global_Lbl_EndDate => GetString("Global_Lbl_EndDate");
    public static string Global_Lbl_Printer => GetString("Global_Lbl_Printer");
    public static string Global_Msg_PrintSent => GetString("Global_Msg_PrintSent");
    public static string Global_Msg_PrintFailed => GetString("Global_Msg_PrintFailed");
    public static string Global_Msg_Printing => GetString("Global_Msg_Printing");
    public static string Global_Msg_PrintError => GetString("Global_Msg_PrintError");
    public static string Global_Msg_SavedAt => GetString("Global_Msg_SavedAt");
    public static string Global_Msg_SaveError => GetString("Global_Msg_SaveError");
    public static string Global_Msg_LoadError => GetString("Global_Msg_LoadError");
    public static string Global_Msg_LoadPrintersError => GetString("Global_Msg_LoadPrintersError");
    public static string Global_Lbl_Language => GetString("Global_Lbl_Language");

    // ==================== LOGIN ====================
    public static string Login_Lbl_Title => GetString("Login_Lbl_Title");
    public static string Login_Lbl_Subtitle => GetString("Login_Lbl_Subtitle");
    public static string Login_Lbl_OperatorCode => GetString("Login_Lbl_OperatorCode");
    public static string Login_Lbl_Pin => GetString("Login_Lbl_Pin");
    public static string Login_Wm_OperatorCode => GetString("Login_Wm_OperatorCode");
    public static string Login_Wm_Pin => GetString("Login_Wm_Pin");
    public static string Login_Btn_Login => GetString("Login_Btn_Login");
    public static string Login_Msg_Authenticating => GetString("Login_Msg_Authenticating");
    public static string Login_Msg_Footer => GetString("Login_Msg_Footer");
    public static string Login_Msg_EnterCode => GetString("Login_Msg_EnterCode");
    public static string Login_Msg_EnterPin => GetString("Login_Msg_EnterPin");
    public static string Login_Msg_InvalidCredentials => GetString("Login_Msg_InvalidCredentials");
    public static string Login_Msg_LoginError => GetString("Login_Msg_LoginError");

    // ==================== HOME ====================
    public static string Home_Lbl_Welcome => GetString("Home_Lbl_Welcome");
    public static string Home_Lbl_SelectOption => GetString("Home_Lbl_SelectOption");
    public static string Home_Lbl_TodaySummary => GetString("Home_Lbl_TodaySummary");
    public static string Home_Lbl_PendingSales => GetString("Home_Lbl_PendingSales");
    public static string Home_Lbl_InProgress => GetString("Home_Lbl_InProgress");
    public static string Home_Lbl_CompletedSales => GetString("Home_Lbl_CompletedSales");
    public static string Home_Lbl_TodaysRevenue => GetString("Home_Lbl_TodaysRevenue");
    public static string Home_Lbl_QuickActions => GetString("Home_Lbl_QuickActions");
    public static string Home_Btn_NewSale => GetString("Home_Btn_NewSale");
    public static string Home_Btn_NewSaleHint => GetString("Home_Btn_NewSaleHint");
    public static string Home_Btn_Products => GetString("Home_Btn_Products");
    public static string Home_Btn_ProductsHint => GetString("Home_Btn_ProductsHint");
    public static string Home_Btn_SalesHistory => GetString("Home_Btn_SalesHistory");
    public static string Home_Btn_SalesHistoryHint => GetString("Home_Btn_SalesHistoryHint");
    public static string Home_Btn_Settings => GetString("Home_Btn_Settings");
    public static string Home_Btn_SettingsHint => GetString("Home_Btn_SettingsHint");
    public static string Home_Lbl_KeyboardShortcuts => GetString("Home_Lbl_KeyboardShortcuts");
    public static string Home_Lbl_OpenCheckout => GetString("Home_Lbl_OpenCheckout");
    public static string Home_Lbl_OpenProducts => GetString("Home_Lbl_OpenProducts");
    public static string Home_Lbl_SalesHistoryShort => GetString("Home_Lbl_SalesHistoryShort");
    public static string Home_Lbl_ReturnToHome => GetString("Home_Lbl_ReturnToHome");
    public static string Home_Lbl_Operator => GetString("Home_Lbl_Operator");

    // ==================== NAV ====================
    public static string Nav_Lbl_PointOfSale => GetString("Nav_Lbl_PointOfSale");
    public static string Nav_Btn_Home => GetString("Nav_Btn_Home");
    public static string Nav_Btn_Checkout => GetString("Nav_Btn_Checkout");
    public static string Nav_Btn_Cadastros => GetString("Nav_Btn_Cadastros");
    public static string Nav_Btn_Products => GetString("Nav_Btn_Products");
    public static string Nav_Btn_Financeiro => GetString("Nav_Btn_Financeiro");
    public static string Nav_Btn_SalesHistory => GetString("Nav_Btn_SalesHistory");
    public static string Nav_Btn_FiscalHistory => GetString("Nav_Btn_FiscalHistory");
    public static string Nav_Btn_Settings => GetString("Nav_Btn_Settings");
    public static string Nav_Btn_FiscalConfig => GetString("Nav_Btn_FiscalConfig");
    public static string Nav_Tip_Logout => GetString("Nav_Tip_Logout");
    public static string Nav_Dlg_SaleInProgress => GetString("Nav_Dlg_SaleInProgress");
    public static string Nav_Dlg_SaleInProgressMsg => GetString("Nav_Dlg_SaleInProgressMsg");
    public static string Nav_Btn_LeaveAnyway => GetString("Nav_Btn_LeaveAnyway");
    public static string Nav_Lbl_WindowTitle => GetString("Nav_Lbl_WindowTitle");

    // ==================== PDV ====================
    public static string PDV_Lbl_Title => GetString("PDV_Lbl_Title");
    public static string PDV_Lbl_SaleInfo => GetString("PDV_Lbl_SaleInfo");
    public static string PDV_Tip_BackToMenu => GetString("PDV_Tip_BackToMenu");
    public static string PDV_Btn_Menu => GetString("PDV_Btn_Menu");
    public static string PDV_Wm_Barcode => GetString("PDV_Wm_Barcode");
    public static string PDV_Btn_Add => GetString("PDV_Btn_Add");
    public static string PDV_Btn_Search => GetString("PDV_Btn_Search");
    public static string PDV_Col_Seq => GetString("PDV_Col_Seq");
    public static string PDV_Col_Barcode => GetString("PDV_Col_Barcode");
    public static string PDV_Col_Description => GetString("PDV_Col_Description");
    public static string PDV_Col_Qty => GetString("PDV_Col_Qty");
    public static string PDV_Col_Price => GetString("PDV_Col_Price");
    public static string PDV_Col_Total => GetString("PDV_Col_Total");
    public static string PDV_Lbl_OrderSummary => GetString("PDV_Lbl_OrderSummary");
    public static string PDV_Lbl_Subtotal => GetString("PDV_Lbl_Subtotal");
    public static string PDV_Lbl_Discount => GetString("PDV_Lbl_Discount");
    public static string PDV_Lbl_Total => GetString("PDV_Lbl_Total");
    public static string PDV_Lbl_AmountReceived => GetString("PDV_Lbl_AmountReceived");
    public static string PDV_Lbl_Change => GetString("PDV_Lbl_Change");
    public static string PDV_Btn_Cash => GetString("PDV_Btn_Cash");
    public static string PDV_Btn_CreditCard => GetString("PDV_Btn_CreditCard");
    public static string PDV_Btn_DebitCard => GetString("PDV_Btn_DebitCard");
    public static string PDV_Btn_Pix => GetString("PDV_Btn_Pix");
    public static string PDV_Btn_CancelSale => GetString("PDV_Btn_CancelSale");
    public static string PDV_Btn_NewSale => GetString("PDV_Btn_NewSale");
    public static string PDV_Lbl_Shortcuts => GetString("PDV_Lbl_Shortcuts");
    public static string PDV_Msg_Ready => GetString("PDV_Msg_Ready");
    public static string PDV_Msg_ReadyScan => GetString("PDV_Msg_ReadyScan");
    public static string PDV_Msg_NoOperator => GetString("PDV_Msg_NoOperator");
    public static string PDV_Msg_PendingSalesCount => GetString("PDV_Msg_PendingSalesCount");
    public static string PDV_Msg_InitError => GetString("PDV_Msg_InitError");
    public static string PDV_Msg_SaleNotFound => GetString("PDV_Msg_SaleNotFound");
    public static string PDV_Msg_ResumedSale => GetString("PDV_Msg_ResumedSale");
    public static string PDV_Msg_ResumeError => GetString("PDV_Msg_ResumeError");
    public static string PDV_Msg_DiscardedSales => GetString("PDV_Msg_DiscardedSales");
    public static string PDV_Msg_DiscardError => GetString("PDV_Msg_DiscardError");
    public static string PDV_Msg_ReadyNewSale => GetString("PDV_Msg_ReadyNewSale");
    public static string PDV_Msg_NewSaleStarted => GetString("PDV_Msg_NewSaleStarted");
    public static string PDV_Msg_StartSaleError => GetString("PDV_Msg_StartSaleError");
    public static string PDV_Msg_ProductNotFound => GetString("PDV_Msg_ProductNotFound");
    public static string PDV_Msg_ProductNotInDb => GetString("PDV_Msg_ProductNotInDb");
    public static string PDV_Msg_Added => GetString("PDV_Msg_Added");
    public static string PDV_Msg_ItemRemoved => GetString("PDV_Msg_ItemRemoved");
    public static string PDV_Msg_RemoveError => GetString("PDV_Msg_RemoveError");
    public static string PDV_Msg_QtyUpdated => GetString("PDV_Msg_QtyUpdated");
    public static string PDV_Msg_QtyError => GetString("PDV_Msg_QtyError");
    public static string PDV_Msg_NoItems => GetString("PDV_Msg_NoItems");
    public static string PDV_Msg_SelectPayment => GetString("PDV_Msg_SelectPayment");
    public static string PDV_Msg_InvalidPayment => GetString("PDV_Msg_InvalidPayment");
    public static string PDV_Msg_SaleCompleted => GetString("PDV_Msg_SaleCompleted");
    public static string PDV_Msg_SaleCompletedChange => GetString("PDV_Msg_SaleCompletedChange");
    public static string PDV_Msg_Remaining => GetString("PDV_Msg_Remaining");
    public static string PDV_Msg_PaymentError => GetString("PDV_Msg_PaymentError");
    public static string PDV_Msg_SaleCancelled => GetString("PDV_Msg_SaleCancelled");
    public static string PDV_Msg_CancelError => GetString("PDV_Msg_CancelError");
    public static string PDV_Msg_ReturnedToSale => GetString("PDV_Msg_ReturnedToSale");
    public static string PDV_Msg_CancelCurrentError => GetString("PDV_Msg_CancelCurrentError");
    public static string PDV_Msg_SearchError => GetString("PDV_Msg_SearchError");
    public static string PDV_Msg_NfceContingency => GetString("PDV_Msg_NfceContingency");
    public static string PDV_Msg_NfceAuthorized => GetString("PDV_Msg_NfceAuthorized");
    public static string PDV_Msg_FiscalError => GetString("PDV_Msg_FiscalError");
    public static string PDV_Msg_FiscalProcessError => GetString("PDV_Msg_FiscalProcessError");
    public static string PDV_Msg_ReceiptError => GetString("PDV_Msg_ReceiptError");
    public static string PDV_Msg_PrintSent => GetString("PDV_Msg_PrintSent");
    public static string PDV_Msg_PrintFailed => GetString("PDV_Msg_PrintFailed");
    public static string PDV_Dlg_PendingSalesTitle => GetString("PDV_Dlg_PendingSalesTitle");
    public static string PDV_Dlg_PendingSalesMsg => GetString("PDV_Dlg_PendingSalesMsg");
    public static string PDV_Btn_Resume => GetString("PDV_Btn_Resume");
    public static string PDV_Btn_DiscardAll => GetString("PDV_Btn_DiscardAll");
    public static string PDV_Btn_StartNewKeep => GetString("PDV_Btn_StartNewKeep");
    public static string PDV_Dlg_CancelSaleTitle => GetString("PDV_Dlg_CancelSaleTitle");
    public static string PDV_Dlg_CancelSaleMsg => GetString("PDV_Dlg_CancelSaleMsg");
    public static string PDV_Btn_NoKeepSale => GetString("PDV_Btn_NoKeepSale");
    public static string PDV_Btn_YesCancelSale => GetString("PDV_Btn_YesCancelSale");
    public static string PDV_Dlg_NewSaleTitle => GetString("PDV_Dlg_NewSaleTitle");
    public static string PDV_Dlg_NewSaleMsg => GetString("PDV_Dlg_NewSaleMsg");
    public static string PDV_Btn_NoKeepCurrent => GetString("PDV_Btn_NoKeepCurrent");
    public static string PDV_Btn_YesStartNew => GetString("PDV_Btn_YesStartNew");
    public static string PDV_Search_Title => GetString("PDV_Search_Title");
    public static string PDV_Search_ResultCount => GetString("PDV_Search_ResultCount");
    public static string PDV_Search_Watermark => GetString("PDV_Search_Watermark");
    public static string PDV_Search_NoResults => GetString("PDV_Search_NoResults");
    public static string PDV_Search_ClickToAdd => GetString("PDV_Search_ClickToAdd");
    public static string PDV_Search_Code => GetString("PDV_Search_Code");
    public static string PDV_Search_Stock => GetString("PDV_Search_Stock");
    public static string PDV_Search_CodeLabel => GetString("PDV_Search_CodeLabel");
    public static string PDV_Search_StockLabel => GetString("PDV_Search_StockLabel");
    public static string PDV_Receipt_Title => GetString("PDV_Receipt_Title");
    public static string PDV_Receipt_SaleNumber => GetString("PDV_Receipt_SaleNumber");
    public static string PDV_Receipt_NfceNumber => GetString("PDV_Receipt_NfceNumber");
    public static string PDV_Receipt_Contingency => GetString("PDV_Receipt_Contingency");
    public static string PDV_Receipt_Authorized => GetString("PDV_Receipt_Authorized");
    public static string PDV_Receipt_BtnSave => GetString("PDV_Receipt_BtnSave");
    public static string PDV_Receipt_BtnPrintAndClose => GetString("PDV_Receipt_BtnPrintAndClose");
    public static string PDV_Pending_SaleInfo => GetString("PDV_Pending_SaleInfo");
    public static string PDV_Pending_ItemsAge => GetString("PDV_Pending_ItemsAge");

    // ==================== PRODUCTS ====================
    public static string Products_Lbl_Title => GetString("Products_Lbl_Title");
    public static string Products_Lbl_Subtitle => GetString("Products_Lbl_Subtitle");
    public static string Products_Btn_NewProduct => GetString("Products_Btn_NewProduct");
    public static string Products_Wm_Search => GetString("Products_Wm_Search");
    public static string Products_Btn_Refresh => GetString("Products_Btn_Refresh");
    public static string Products_Col_Barcode => GetString("Products_Col_Barcode");
    public static string Products_Col_Description => GetString("Products_Col_Description");
    public static string Products_Col_Price => GetString("Products_Col_Price");
    public static string Products_Col_Stock => GetString("Products_Col_Stock");
    public static string Products_Col_Unit => GetString("Products_Col_Unit");
    public static string Products_Col_Active => GetString("Products_Col_Active");
    public static string Products_Lbl_QuickStockAdj => GetString("Products_Lbl_QuickStockAdj");
    public static string Products_Lbl_CurrentStock => GetString("Products_Lbl_CurrentStock");
    public static string Products_Lbl_Adjustment => GetString("Products_Lbl_Adjustment");
    public static string Products_Btn_ApplyAdjustment => GetString("Products_Btn_ApplyAdjustment");
    public static string Products_Msg_SelectToAdjust => GetString("Products_Msg_SelectToAdjust");
    public static string Products_Lbl_NewProduct => GetString("Products_Lbl_NewProduct");
    public static string Products_Lbl_EditProduct => GetString("Products_Lbl_EditProduct");
    public static string Products_Lbl_Barcode => GetString("Products_Lbl_Barcode");
    public static string Products_Lbl_UnitOfMeasure => GetString("Products_Lbl_UnitOfMeasure");
    public static string Products_Lbl_Description => GetString("Products_Lbl_Description");
    public static string Products_Lbl_ShortDescription => GetString("Products_Lbl_ShortDescription");
    public static string Products_Lbl_UnitPrice => GetString("Products_Lbl_UnitPrice");
    public static string Products_Lbl_StockQuantity => GetString("Products_Lbl_StockQuantity");
    public static string Products_Lbl_TaxCode => GetString("Products_Lbl_TaxCode");
    public static string Products_Lbl_TaxRate => GetString("Products_Lbl_TaxRate");
    public static string Products_Lbl_IsActive => GetString("Products_Lbl_IsActive");
    public static string Products_Btn_CancelEdit => GetString("Products_Btn_CancelEdit");
    public static string Products_Btn_SaveProduct => GetString("Products_Btn_SaveProduct");
    public static string Products_Msg_Loading => GetString("Products_Msg_Loading");
    public static string Products_Msg_FoundCount => GetString("Products_Msg_FoundCount");
    public static string Products_Msg_LoadError => GetString("Products_Msg_LoadError");
    public static string Products_Msg_CreatingNew => GetString("Products_Msg_CreatingNew");
    public static string Products_Msg_Editing => GetString("Products_Msg_Editing");
    public static string Products_Msg_BarcodeRequired => GetString("Products_Msg_BarcodeRequired");
    public static string Products_Msg_DescriptionRequired => GetString("Products_Msg_DescriptionRequired");
    public static string Products_Msg_PriceNegative => GetString("Products_Msg_PriceNegative");
    public static string Products_Msg_SaveError => GetString("Products_Msg_SaveError");
    public static string Products_Msg_BarcodeExists => GetString("Products_Msg_BarcodeExists");
    public static string Products_Msg_Created => GetString("Products_Msg_Created");
    public static string Products_Msg_ProductNotFound => GetString("Products_Msg_ProductNotFound");
    public static string Products_Msg_Updated => GetString("Products_Msg_Updated");
    public static string Products_Msg_EditCancelled => GetString("Products_Msg_EditCancelled");
    public static string Products_Msg_Deactivated => GetString("Products_Msg_Deactivated");
    public static string Products_Msg_DeleteError => GetString("Products_Msg_DeleteError");
    public static string Products_Msg_StockUpdated => GetString("Products_Msg_StockUpdated");
    public static string Products_Msg_StockError => GetString("Products_Msg_StockError");

    // ==================== SALES ====================
    public static string Sales_Lbl_Title => GetString("Sales_Lbl_Title");
    public static string Sales_Lbl_Subtitle => GetString("Sales_Lbl_Subtitle");
    public static string Sales_Btn_Search => GetString("Sales_Btn_Search");
    public static string Sales_Lbl_TotalSales => GetString("Sales_Lbl_TotalSales");
    public static string Sales_Lbl_Revenue => GetString("Sales_Lbl_Revenue");
    public static string Sales_Lbl_AvgTicket => GetString("Sales_Lbl_AvgTicket");
    public static string Sales_Lbl_Completed => GetString("Sales_Lbl_Completed");
    public static string Sales_Lbl_Cancelled => GetString("Sales_Lbl_Cancelled");
    public static string Sales_Col_Number => GetString("Sales_Col_Number");
    public static string Sales_Col_Date => GetString("Sales_Col_Date");
    public static string Sales_Col_Total => GetString("Sales_Col_Total");
    public static string Sales_Col_Items => GetString("Sales_Col_Items");
    public static string Sales_Col_Status => GetString("Sales_Col_Status");
    public static string Sales_Col_Customer => GetString("Sales_Col_Customer");
    public static string Sales_Lbl_SelectToView => GetString("Sales_Lbl_SelectToView");
    public static string Sales_Lbl_SaleNumber => GetString("Sales_Lbl_SaleNumber");
    public static string Sales_Lbl_Items => GetString("Sales_Lbl_Items");
    public static string Sales_Lbl_Subtotal => GetString("Sales_Lbl_Subtotal");
    public static string Sales_Lbl_Discount => GetString("Sales_Lbl_Discount");
    public static string Sales_Lbl_Total => GetString("Sales_Lbl_Total");
    public static string Sales_Lbl_Payments => GetString("Sales_Lbl_Payments");
    public static string Sales_Msg_SelectAndSearch => GetString("Sales_Msg_SelectAndSearch");
    public static string Sales_Msg_Searching => GetString("Sales_Msg_Searching");
    public static string Sales_Msg_FoundCount => GetString("Sales_Msg_FoundCount");
    public static string Sales_Msg_SaleNotFound => GetString("Sales_Msg_SaleNotFound");
    public static string Sales_Msg_LoadError => GetString("Sales_Msg_LoadError");
    public static string Sales_Status_Completed => GetString("Sales_Status_Completed");
    public static string Sales_Status_Cancelled => GetString("Sales_Status_Cancelled");
    public static string Sales_Status_InProgress => GetString("Sales_Status_InProgress");
    public static string Sales_Status_All => GetString("Sales_Status_All");
    public static string Sales_Payment_Cash => GetString("Sales_Payment_Cash");
    public static string Sales_Payment_CreditCard => GetString("Sales_Payment_CreditCard");
    public static string Sales_Payment_DebitCard => GetString("Sales_Payment_DebitCard");
    public static string Sales_Payment_Pix => GetString("Sales_Payment_Pix");
    public static string Sales_Payment_FoodVoucher => GetString("Sales_Payment_FoodVoucher");
    public static string Sales_Payment_MealVoucher => GetString("Sales_Payment_MealVoucher");
    public static string Sales_Payment_Other => GetString("Sales_Payment_Other");

    // ==================== FISCAL ====================
    public static string Fiscal_Lbl_Title => GetString("Fiscal_Lbl_Title");
    public static string Fiscal_Lbl_Subtitle => GetString("Fiscal_Lbl_Subtitle");
    public static string Fiscal_Lbl_CompanyData => GetString("Fiscal_Lbl_CompanyData");
    public static string Fiscal_Lbl_TaxId => GetString("Fiscal_Lbl_TaxId");
    public static string Fiscal_Wm_TaxId => GetString("Fiscal_Wm_TaxId");
    public static string Fiscal_Lbl_StateRegistration => GetString("Fiscal_Lbl_StateRegistration");
    public static string Fiscal_Lbl_LegalName => GetString("Fiscal_Lbl_LegalName");
    public static string Fiscal_Lbl_TradeName => GetString("Fiscal_Lbl_TradeName");
    public static string Fiscal_Lbl_State => GetString("Fiscal_Lbl_State");
    public static string Fiscal_Lbl_TaxRegime => GetString("Fiscal_Lbl_TaxRegime");
    public static string Fiscal_Lbl_Address => GetString("Fiscal_Lbl_Address");
    public static string Fiscal_Lbl_Street => GetString("Fiscal_Lbl_Street");
    public static string Fiscal_Lbl_AddressNumber => GetString("Fiscal_Lbl_AddressNumber");
    public static string Fiscal_Lbl_Neighborhood => GetString("Fiscal_Lbl_Neighborhood");
    public static string Fiscal_Lbl_ZipCode => GetString("Fiscal_Lbl_ZipCode");
    public static string Fiscal_Wm_ZipCode => GetString("Fiscal_Wm_ZipCode");
    public static string Fiscal_Lbl_CityCode => GetString("Fiscal_Lbl_CityCode");
    public static string Fiscal_Wm_CityCode => GetString("Fiscal_Wm_CityCode");
    public static string Fiscal_Lbl_NfceParams => GetString("Fiscal_Lbl_NfceParams");
    public static string Fiscal_Lbl_Series => GetString("Fiscal_Lbl_Series");
    public static string Fiscal_Lbl_NextNumber => GetString("Fiscal_Lbl_NextNumber");
    public static string Fiscal_Lbl_Environment => GetString("Fiscal_Lbl_Environment");
    public static string Fiscal_Lbl_Homologation => GetString("Fiscal_Lbl_Homologation");
    public static string Fiscal_Lbl_Production => GetString("Fiscal_Lbl_Production");
    public static string Fiscal_Lbl_CscId => GetString("Fiscal_Lbl_CscId");
    public static string Fiscal_Lbl_CscToken => GetString("Fiscal_Lbl_CscToken");
    public static string Fiscal_Lbl_CertPath => GetString("Fiscal_Lbl_CertPath");
    public static string Fiscal_Wm_CertPath => GetString("Fiscal_Wm_CertPath");
    public static string Fiscal_Lbl_CertPassword => GetString("Fiscal_Lbl_CertPassword");
    public static string Fiscal_Btn_TestConnection => GetString("Fiscal_Btn_TestConnection");
    public static string Fiscal_Btn_SaveConfig => GetString("Fiscal_Btn_SaveConfig");
    public static string Fiscal_Msg_Loading => GetString("Fiscal_Msg_Loading");
    public static string Fiscal_Msg_Loaded => GetString("Fiscal_Msg_Loaded");
    public static string Fiscal_Msg_NoConfig => GetString("Fiscal_Msg_NoConfig");
    public static string Fiscal_Msg_Saving => GetString("Fiscal_Msg_Saving");
    public static string Fiscal_Msg_Saved => GetString("Fiscal_Msg_Saved");
    public static string Fiscal_Msg_TestingConnection => GetString("Fiscal_Msg_TestingConnection");
    public static string Fiscal_Msg_ConnectionOk => GetString("Fiscal_Msg_ConnectionOk");
    public static string Fiscal_Msg_SefazUnavailable => GetString("Fiscal_Msg_SefazUnavailable");
    public static string Fiscal_Msg_TestError => GetString("Fiscal_Msg_TestError");
    public static string Fiscal_Msg_TaxIdRequired => GetString("Fiscal_Msg_TaxIdRequired");
    public static string Fiscal_Msg_TaxIdLength => GetString("Fiscal_Msg_TaxIdLength");
    public static string Fiscal_Msg_LegalNameRequired => GetString("Fiscal_Msg_LegalNameRequired");
    public static string Fiscal_Msg_TradeNameRequired => GetString("Fiscal_Msg_TradeNameRequired");
    public static string Fiscal_Msg_StateRequired => GetString("Fiscal_Msg_StateRequired");
    public static string Fiscal_Msg_CityCodeLength => GetString("Fiscal_Msg_CityCodeLength");
    public static string Fiscal_Msg_AddressRequired => GetString("Fiscal_Msg_AddressRequired");
    public static string Fiscal_Msg_NumberRequired => GetString("Fiscal_Msg_NumberRequired");
    public static string Fiscal_Msg_ZipCodeRequired => GetString("Fiscal_Msg_ZipCodeRequired");
    public static string Fiscal_Msg_SeriesRequired => GetString("Fiscal_Msg_SeriesRequired");
    public static string Fiscal_TaxRegime_SimplesNacional => GetString("Fiscal_TaxRegime_SimplesNacional");
    public static string Fiscal_TaxRegime_SimplesExcesso => GetString("Fiscal_TaxRegime_SimplesExcesso");
    public static string Fiscal_TaxRegime_Normal => GetString("Fiscal_TaxRegime_Normal");

    // ==================== FISCAL HISTORY ====================
    public static string FiscalHist_Lbl_Title => GetString("FiscalHist_Lbl_Title");
    public static string FiscalHist_Lbl_Subtitle => GetString("FiscalHist_Lbl_Subtitle");
    public static string FiscalHist_Lbl_AccessKey => GetString("FiscalHist_Lbl_AccessKey");
    public static string FiscalHist_Wm_AccessKey => GetString("FiscalHist_Wm_AccessKey");
    public static string FiscalHist_Btn_Search => GetString("FiscalHist_Btn_Search");
    public static string FiscalHist_Col_Nfce => GetString("FiscalHist_Col_Nfce");
    public static string FiscalHist_Col_Series => GetString("FiscalHist_Col_Series");
    public static string FiscalHist_Col_Date => GetString("FiscalHist_Col_Date");
    public static string FiscalHist_Col_Value => GetString("FiscalHist_Col_Value");
    public static string FiscalHist_Col_Status => GetString("FiscalHist_Col_Status");
    public static string FiscalHist_Col_Key => GetString("FiscalHist_Col_Key");
    public static string FiscalHist_Lbl_Authorized => GetString("FiscalHist_Lbl_Authorized");
    public static string FiscalHist_Lbl_Contingency => GetString("FiscalHist_Lbl_Contingency");
    public static string FiscalHist_Lbl_Cancelled => GetString("FiscalHist_Lbl_Cancelled");
    public static string FiscalHist_Lbl_SelectTransaction => GetString("FiscalHist_Lbl_SelectTransaction");
    public static string FiscalHist_Lbl_ToViewDetails => GetString("FiscalHist_Lbl_ToViewDetails");
    public static string FiscalHist_Lbl_NfceNumber => GetString("FiscalHist_Lbl_NfceNumber");
    public static string FiscalHist_Lbl_StatusLabel => GetString("FiscalHist_Lbl_StatusLabel");
    public static string FiscalHist_Lbl_ContingencyWarning => GetString("FiscalHist_Lbl_ContingencyWarning");
    public static string FiscalHist_Lbl_PendingTransmission => GetString("FiscalHist_Lbl_PendingTransmission");
    public static string FiscalHist_Lbl_Protocol => GetString("FiscalHist_Lbl_Protocol");
    public static string FiscalHist_Lbl_AuthorizedAt => GetString("FiscalHist_Lbl_AuthorizedAt");
    public static string FiscalHist_Lbl_AccessKeyTitle => GetString("FiscalHist_Lbl_AccessKeyTitle");
    public static string FiscalHist_Lbl_Reprints => GetString("FiscalHist_Lbl_Reprints");
    public static string FiscalHist_Lbl_ReprintTotal => GetString("FiscalHist_Lbl_ReprintTotal");
    public static string FiscalHist_Lbl_ReprintBy => GetString("FiscalHist_Lbl_ReprintBy");
    public static string FiscalHist_Btn_ReprintDanfe => GetString("FiscalHist_Btn_ReprintDanfe");
    public static string FiscalHist_Btn_OpenAsPdf => GetString("FiscalHist_Btn_OpenAsPdf");
    public static string FiscalHist_Btn_SavePdf => GetString("FiscalHist_Btn_SavePdf");
    public static string FiscalHist_Lbl_ThermalPrinter => GetString("FiscalHist_Lbl_ThermalPrinter");
    public static string FiscalHist_Wm_SelectPrinter => GetString("FiscalHist_Wm_SelectPrinter");
    public static string FiscalHist_Lbl_QrCodeSize => GetString("FiscalHist_Lbl_QrCodeSize");
    public static string FiscalHist_Btn_PrintThermal => GetString("FiscalHist_Btn_PrintThermal");
    public static string FiscalHist_Btn_TestQrCode => GetString("FiscalHist_Btn_TestQrCode");
    public static string FiscalHist_Dlg_ReprintTitle => GetString("FiscalHist_Dlg_ReprintTitle");
    public static string FiscalHist_Dlg_ReprintReasonPrompt => GetString("FiscalHist_Dlg_ReprintReasonPrompt");
    public static string FiscalHist_Wm_ReprintReason => GetString("FiscalHist_Wm_ReprintReason");
    public static string FiscalHist_Dlg_AuditInfo => GetString("FiscalHist_Dlg_AuditInfo");
    public static string FiscalHist_Msg_SelectPeriod => GetString("FiscalHist_Msg_SelectPeriod");
    public static string FiscalHist_Msg_Searching => GetString("FiscalHist_Msg_Searching");
    public static string FiscalHist_Msg_FoundOne => GetString("FiscalHist_Msg_FoundOne");
    public static string FiscalHist_Msg_NotFoundByKey => GetString("FiscalHist_Msg_NotFoundByKey");
    public static string FiscalHist_Msg_FoundCount => GetString("FiscalHist_Msg_FoundCount");
    public static string FiscalHist_Msg_TransactionNotFound => GetString("FiscalHist_Msg_TransactionNotFound");
    public static string FiscalHist_Msg_DetailError => GetString("FiscalHist_Msg_DetailError");
    public static string FiscalHist_Msg_SelectFirst => GetString("FiscalHist_Msg_SelectFirst");
    public static string FiscalHist_Msg_NoTransaction => GetString("FiscalHist_Msg_NoTransaction");
    public static string FiscalHist_Msg_NotLoggedIn => GetString("FiscalHist_Msg_NotLoggedIn");
    public static string FiscalHist_Msg_ReprintError => GetString("FiscalHist_Msg_ReprintError");
    public static string FiscalHist_Msg_ReprintEscPos => GetString("FiscalHist_Msg_ReprintEscPos");
    public static string FiscalHist_Msg_WithNativeQr => GetString("FiscalHist_Msg_WithNativeQr");
    public static string FiscalHist_Msg_EscPosFailed => GetString("FiscalHist_Msg_EscPosFailed");
    public static string FiscalHist_Msg_SelectThermal => GetString("FiscalHist_Msg_SelectThermal");
    public static string FiscalHist_Msg_PdfOpened => GetString("FiscalHist_Msg_PdfOpened");
    public static string FiscalHist_Msg_PdfUnavailable => GetString("FiscalHist_Msg_PdfUnavailable");
    public static string FiscalHist_Msg_ReprintSentToPrinter => GetString("FiscalHist_Msg_ReprintSentToPrinter");
    public static string FiscalHist_Msg_QrCodeAvailPdf => GetString("FiscalHist_Msg_QrCodeAvailPdf");
    public static string FiscalHist_Msg_ReprintFinalError => GetString("FiscalHist_Msg_ReprintFinalError");
    public static string FiscalHist_Msg_PdfError => GetString("FiscalHist_Msg_PdfError");
    public static string FiscalHist_Msg_PdfSaved => GetString("FiscalHist_Msg_PdfSaved");
    public static string FiscalHist_Msg_PdfSaveError => GetString("FiscalHist_Msg_PdfSaveError");
    public static string FiscalHist_Msg_ThermalNotAvailable => GetString("FiscalHist_Msg_ThermalNotAvailable");
    public static string FiscalHist_Msg_SelectPrinterFirst => GetString("FiscalHist_Msg_SelectPrinterFirst");
    public static string FiscalHist_Msg_TestingQr => GetString("FiscalHist_Msg_TestingQr");
    public static string FiscalHist_Msg_TestQrSuccess => GetString("FiscalHist_Msg_TestQrSuccess");
    public static string FiscalHist_Msg_TestQrFailed => GetString("FiscalHist_Msg_TestQrFailed");
    public static string FiscalHist_Msg_TestQrError => GetString("FiscalHist_Msg_TestQrError");
    public static string FiscalHist_Status_Pending => GetString("FiscalHist_Status_Pending");
    public static string FiscalHist_Status_Authorized => GetString("FiscalHist_Status_Authorized");
    public static string FiscalHist_Status_Rejected => GetString("FiscalHist_Status_Rejected");
    public static string FiscalHist_Status_Cancelled => GetString("FiscalHist_Status_Cancelled");
    public static string FiscalHist_Status_Contingency => GetString("FiscalHist_Status_Contingency");
    public static string FiscalHist_StatusOpt_All => GetString("FiscalHist_StatusOpt_All");
    public static string FiscalHist_StatusOpt_Authorized => GetString("FiscalHist_StatusOpt_Authorized");
    public static string FiscalHist_StatusOpt_Contingency => GetString("FiscalHist_StatusOpt_Contingency");
    public static string FiscalHist_StatusOpt_Cancelled => GetString("FiscalHist_StatusOpt_Cancelled");
    public static string FiscalHist_StatusOpt_Rejected => GetString("FiscalHist_StatusOpt_Rejected");
    public static string FiscalHist_Lbl_UnknownOperator => GetString("FiscalHist_Lbl_UnknownOperator");
    public static string FiscalHist_Msg_SavePdfConsult => GetString("FiscalHist_Msg_SavePdfConsult");

    // ==================== RECEIPT ====================
    public static string Receipt_Lbl_Title => GetString("Receipt_Lbl_Title");
    public static string Receipt_Lbl_SaleNumber => GetString("Receipt_Lbl_SaleNumber");
    public static string Receipt_Lbl_TotalFormat => GetString("Receipt_Lbl_TotalFormat");
    public static string Receipt_Lbl_Contingency => GetString("Receipt_Lbl_Contingency");
    public static string Receipt_Lbl_Authorized => GetString("Receipt_Lbl_Authorized");
    public static string Receipt_Btn_SaveFile => GetString("Receipt_Btn_SaveFile");
    public static string Receipt_Btn_PrintAndClose => GetString("Receipt_Btn_PrintAndClose");
    public static string Receipt_Msg_NfceContingency => GetString("Receipt_Msg_NfceContingency");
    public static string Receipt_Msg_NfceNormal => GetString("Receipt_Msg_NfceNormal");
    public static string Receipt_Msg_NoContent => GetString("Receipt_Msg_NoContent");
}
